[package]
name = "policy"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
ahash.workspace = true
grafbase-sdk.workspace = true
log.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
grafbase-sdk = { workspace = true, features = ["test-utils"] }
insta = { workspace = true, features = ["json"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "test-util"] }
wiremock.workspace = true
