[package]
name = "my-authorization"
version = "1.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
grafbase-sdk.workspace = true
http.workspace = true
itertools.workspace = true
postcard.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
