[package]
name = "my-authorization"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
grafbase-sdk.workspace = true
http.workspace = true
itertools.workspace = true
log.workspace = true
postcard.workspace = true
rkyv.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
