[package]
name = "auth-09"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
grafbase-sdk = "0.9.1"
serde.workspace = true
serde_json.workspace = true

[lib]
crate-type = ["cdylib"]

[dev-dependencies]
grafbase-sdk = { version = "0.9.1", features = ["test-utils"] }
