[package]
name = "resolver-08"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
grafbase-sdk = "0.8.0"
serde.workspace = true

[dev-dependencies]
grafbase-sdk = { version = "0.8.0", features = ["test-utils"] }
indoc = "2"
insta = { version = "1.42.2", features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "test-util"] }
