[package]
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license = "MPL-2.0"
name = "gateway-config"
repository.workspace = true

[lints]
workspace = true

[dependencies]
ascii = { workspace = true, features = ["serde"] }
cfg-if.workspace = true
chrono.workspace = true
duration-str.workspace = true
grafbase-workspace-hack.workspace = true
http.workspace = true
regex.workspace = true
semver = { workspace = true, features = ["serde"] }
serde.workspace = true
serde-dynamic-string.workspace = true
serde_regex.workspace = true
size.workspace = true
toml.workspace = true
tonic = { workspace = true, features = ["tls-roots"] }
tower-http = { workspace = true, features = ["cors", "timeout"] }
url = { workspace = true, features = ["serde"] }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
temp-env.workspace = true
tempfile.workspace = true
toml.workspace = true
