services:
  sse-subgraph:
    restart: unless-stopped
    build:
      context: ./data/sse-subgraph
    ports:
      - '4092:4092'

  gqlgen-subgraph:
    restart: unless-stopped
    build:
      context: ./data/gqlgen-subgraph
    ports:
      - '8080:8080'

  mtls-subgraph:
    build:
      context: ./data/mtls-subgraph
    ports:
      - '8081:3001'
    volumes:
      - ./data/mtls-subgraph/certs:/app/certs
    restart: unless-stopped
    environment:
      - RUST_LOG=info
