[subgraphs.routeguide]
schema_path = "./schema.graphql"

[subgraphs.other]
schema_path = "./other.graphql"

[extensions.grpc]
version = "0.1.0"

[[extensions.grpc.config.services]]
name = "routeguide.RouteGuide"
address = "http://localhost:10000"
