name: Fetch CLI assets
description: Fetches assets for the Grafbase CLI

runs:
  using: 'composite'
  steps:
    - name: Download CLI assets
      shell: bash
      run: |
        CACHE_BREAKER=$(openssl rand -hex 8)
        pushd cli/assets
        curl -H "Cache-Control: must-revalidate, post-check=0, pre-check=0" -o cli-app.tar.gz http://downloads.grafbase.com/cli-app/cli-app.tar.gz?cache=$CACHE_BREAKER
        popd
