[extension]
name = "nats"
version = "0.3.0"
kind = "resolver"
description = "Map NATS endpoints to GraphQL fields. Supports regular and JetStream subscriptions, as well as request/reply messaging and the key/value store."

[directives]
definitions = "definitions.graphql"
field_resolvers = ["natsPublish", "natsSubscription", "natsRequest", "natsKeyValue"]

[permissions]
network = true
