[package]
name = "federation-audit-tests"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

[dependencies]
grafbase-workspace-hack.workspace = true
reqwest.features = ["blocking"]
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
cynic-parser = { workspace = true, features = ["pretty"] }
graphql-composition.workspace = true
integration-tests = { path = "../integration-tests" }
libtest-mimic.workspace = true
similar-asserts.workspace = true

[lints]
workspace = true

[[test]]
name = "audit_tests"
harness = false

[[test]]
name = "composition_comparisons"
harness = false
