[profile.ci]
# grafbase extension build test compile tons of stuff and thus a super slow.
slow-timeout = { period = "1m", terminate-after = 3 }
retries = 2
failure-output = "immediate-final"
fail-fast = false

[[profile.ci.overrides]]
# Telemetry ones tend to be flaky, not sure how to specify only the telemetry ones though...
filter = 'package(grafbase-gateway)'
retries = 2

[[profile.ci.overrides]]
# Some federation audit tests should not be retried as they are self fixing
# and will always pass on a retry
filter = 'package(federation-audit-tests) & (binary(checkout) | binary(cache_freshness))'
retries = 0

[profile.ci.junit]
# output test results at target/nextest/ci/junit.xml
path = "junit.xml"
store-success-output = true
store-failure-output = true

[test-groups]
# Extension build are huge consumers of CPU as they build complete Rust projects.
# We could be more fine-grained, but in grand scheme of things, it doesn't matter.
grafbase-extension-tests = { max-threads = 2 }

[[profile.default.overrides]]
filter = 'package(grafbase) & binary(integration_tests) & (test(extension::) | test(dev::))'
test-group = 'grafbase-extension-tests'

