[package]
name = "my-authentication"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
grafbase-sdk.workspace = true
postcard.workspace = true
