[package]
name = "my-authentication"
version = "1.0.0"
edition = "2024"
license = "Apache-2.0"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
common.workspace = true
grafbase-sdk.workspace = true
postcard.workspace = true
