[package]
name = "hooks"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
grafbase-sdk = { path = "../../../crates/grafbase-sdk" }
postcard = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
grafbase-sdk = { path = "../../../crates/grafbase-sdk", features = ["test-utils"] }
insta = { version = "1", features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "test-util"] }
