[package]
name = "operation-normalizer"
edition.workspace = true
license.workspace = true
homepage.workspace = true
keywords.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cynic-parser.workspace = true
grafbase-workspace-hack.workspace = true
graphql-parser.workspace = true

[lints]
workspace = true

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
