[workspace]
resolver = "2"
members = [
    "authentication",
    "authorization",
    "common",
    "policy",
]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[workspace.dependencies]
ahash = "0.8"
common = { path = "common" }
grafbase-sdk = "0.19.2"
http = "1"
insta = "1"
itertools = "0.14"
log = "0.4"
postcard = { version = "1", features = ["use-std"] }
rkyv = "0.8"
serde = "1"
serde_json = "1"
serde_with = "3"
tokio = "1"
wiremock = "0.6"
