[package]
name = "geo"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
strip = true
lto = true
codegen-units = 1

[dependencies]
grafbase-sdk = "0.17.4"
itertools = "0.14"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
grafbase-sdk = { version = "0.17.4", features = ["test-utils"] }
indoc = "2"
insta = { version = "1", features = ["json"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "test-util"] }
