[graph]
introspection = true

[hooks]
location = "target/wasm32-wasip2/release/hooks.wasm"
stdout = true
stderr = true
environment_variables = true
networking = true

[subgraphs.pets]
introspection_url = "http://localhost:4002/graphql"
