[subgraphs.users]
url = "http://localhost:4000/graphql"
schema_path = "./subgraphs/users/schema.graphql"

[extensions]
my-authentication.path = "./extensions/authentication/build"

[extensions.my-authorization]
path = "./extensions/authorization/build"

[extensions.my-authorization.config]
auth_service_url = "{{ env.AUTH_SERVICE_URL }}"

